# Master pipeline notebook

This notebook is mainly meant to run the experimentation. 

The experimentation is divided into seperate parts according to machine learning process

The process involves: 
1. Data gathering and initial transformation
2. Data analysis
3. feature engineering 
4. Modelling 
5. Evaluation

In [1]:
import numpy as np
import pandas as pd
from data import gatherData
import plotly.graph_objects as go
from pre_process_data import processData
from feature import engineerFeaturesForTraining, splitData
from transform import transformData
from utils import load_config_file
from train import train
import torch
from LSTM_model import LSTM
from inference import makeInference

In [2]:
config = load_config_file("config.yml")
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

## 1. Data gathering and transformation

This stage is mainly to gather the data. Combine them if necessary. Perform initial data wrangling, so that it is ready for 
data analysis

In [3]:
gather_data_obj = gatherData(config=config)

In [4]:
(
    lap_times_df,
    pit_stops_df,
    qualifying_df,
    races_df,
    results_df,
    sprint_results_df,
    status_df,
) = gather_data_obj.load_data()

In [5]:
pre_process_obj = processData(config=config)

master_lap_times_df = pre_process_obj.create_initial_dataset(
    lap_times_df=lap_times_df, races_df=races_df, results_df=results_df
)
master_lap_times_df

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
0          841        20    1         1         98109  2011      1          1   
1          841        20    2         1         93006  2011      1          1   
2          841        20    3         1         92713  2011      1          1   
3          841        20    4         1         92803  2011      1          1   
4          841        20    5         1         92342  2011      1          1   
...        ...       ...  ...       ...           ...   ...    ...        ...   
551737    1110       817   40        17        114361  2023     12         13   
551738    1110       817   41        17        113367  2023     12         13   
551739    1110       817   42        16        115247  2023     12         13   
551740    1110       817   43        16        112115  2023     12         13   
551741    1110       817   44        16        112265  2023     12         13   

                         name        date number  statusId  
0       Australian Grand Prix  2011-03-27      1         1  
1       Australian Grand Prix  2011-03-27      1         1  
2       Australian Grand Prix  2011-03-27      1         1  
3       Australian Grand Prix  2011-03-27      1         1  
4       Australian Grand Prix  2011-03-27      1         1  
...                       ...         ...    ...       ...  
551737     Belgian Grand Prix  2023-07-30      3         1  
551738     Belgian Grand Prix  2023-07-30      3         1  
551739     Belgian Grand Prix  2023-07-30      3         1  
551740     Belgian Grand Prix  2023-07-30      3         1  
551741     Belgian Grand Prix  2023-07-30      3         1  

[551742 rows x 12 columns]

In [6]:
# check for nans in the data
master_lap_times_df.isna().any()

raceId          False
driverId        False
lap             False
position        False
milliseconds    False
year            False
round           False
circuitId       False
name            False
date            False
number          False
statusId        False
dtype: bool

In [7]:
driver_id = 20
race_id = 841

lap_times_selected_driver_race = master_lap_times_df[
    (master_lap_times_df["raceId"] == race_id)
    & (master_lap_times_df["driverId"] == driver_id)
]

In [8]:
## Lap times and pit stops

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=lap_times_selected_driver_race["lap"],
        y=lap_times_selected_driver_race["milliseconds"],
        mode="lines+markers",
        name="Lap times in milliseconds",
    )
)

fig.update_layout(
    title="Laptimes by each lap", xaxis_title="Lap number", yaxis_title="Total lap time"
)

- Two outliers in the data 
- this is mainly the pit stops that happen in between the race

In [9]:
master_laptimes_pitstop_df = pre_process_obj.add_pitstop_data(
    master_laptime_data=master_lap_times_df, pit_stop_data=pit_stops_df
)
master_laptimes_pitstop_df

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
0          841        20    1         1         98109  2011      1          1   
1          841        20    2         1         93006  2011      1          1   
2          841        20    3         1         92713  2011      1          1   
3          841        20    4         1         92803  2011      1          1   
4          841        20    5         1         92342  2011      1          1   
...        ...       ...  ...       ...           ...   ...    ...        ...   
551737    1110       817   40        17        114361  2023     12         13   
551738    1110       817   41        17        113367  2023     12         13   
551739    1110       817   42        16        115247  2023     12         13   
551740    1110       817   43        16        112115  2023     12         13   
551741    1110       817   44        16        112265  2023     12         13   

                         name        date number  statusId  \
0       Australian Grand Prix  2011-03-27      1         1   
1       Australian Grand Prix  2011-03-27      1         1   
2       Australian Grand Prix  2011-03-27      1         1   
3       Australian Grand Prix  2011-03-27      1         1   
4       Australian Grand Prix  2011-03-27      1         1   
...                       ...         ...    ...       ...   
551737     Belgian Grand Prix  2023-07-30      3         1   
551738     Belgian Grand Prix  2023-07-30      3         1   
551739     Belgian Grand Prix  2023-07-30      3         1   
551740     Belgian Grand Prix  2023-07-30      3         1   
551741     Belgian Grand Prix  2023-07-30      3         1   

        pitStopMilliseconds  isPitStop  
0                       0.0      False  
1                       0.0      False  
2                       0.0      False  
3                       0.0      False  
4                       0.0      False  
...                     ...        ...  
551737                  0.0      False  
551738                  0.0      False  
551739                  0.0      False  
551740                  0.0      False  
551741                  0.0      False  

[551742 rows x 14 columns]

In [10]:
driver_id = 20
circuit_id = 1

lap_times_selected_driver_circuit = master_laptimes_pitstop_df[
    (master_laptimes_pitstop_df["circuitId"] == circuit_id)
    & (master_laptimes_pitstop_df["driverId"] == driver_id)
]

In [11]:
lap_times_selected_driver_circuit

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
0          841        20    1         1         98109  2011      1          1   
1          841        20    2         1         93006  2011      1          1   
2          841        20    3         1         92713  2011      1          1   
3          841        20    4         1         92803  2011      1          1   
4          841        20    5         1         92342  2011      1          1   
...        ...       ...  ...       ...           ...   ...    ...        ...   
517395    1076        20   18        15         85367  2022      3          1   
517396    1076        20   19        15         85503  2022      3          1   
517397    1076        20   20        15         85398  2022      3          1   
517398    1076        20   21        13         85505  2022      3          1   
517399    1076        20   22        12         87005  2022      3          1   

                         name        date number  statusId  \
0       Australian Grand Prix  2011-03-27      1         1   
1       Australian Grand Prix  2011-03-27      1         1   
2       Australian Grand Prix  2011-03-27      1         1   
3       Australian Grand Prix  2011-03-27      1         1   
4       Australian Grand Prix  2011-03-27      1         1   
...                       ...         ...    ...       ...   
517395  Australian Grand Prix  2022-04-10      5         3   
517396  Australian Grand Prix  2022-04-10      5         3   
517397  Australian Grand Prix  2022-04-10      5         3   
517398  Australian Grand Prix  2022-04-10      5         3   
517399  Australian Grand Prix  2022-04-10      5         3   

        pitStopMilliseconds  isPitStop  
0                       0.0      False  
1                       0.0      False  
2                       0.0      False  
3                       0.0      False  
4                       0.0      False  
...                     ...        ...  
517395                  0.0      False  
517396                  0.0      False  
517397                  0.0      False  
517398                  0.0      False  
517399                  0.0      False  

[568 rows x 14 columns]

In [12]:
list_race_id = lap_times_selected_driver_circuit["raceId"].unique().tolist()

In [13]:
## Lap times and pit stops

fig = go.Figure()

for race_id in list_race_id:

    lap_times_race = lap_times_selected_driver_circuit[
        lap_times_selected_driver_circuit["raceId"] == race_id
    ]

    fig.add_trace(
        go.Scatter(
            x=lap_times_race["lap"],
            y=lap_times_race["milliseconds"],
            mode="lines+markers",
            name=f"race id: {race_id}",
        )
    )

    fig.update_layout(
        title="Laptimes by each lap",
        xaxis_title="Lap number",
        yaxis_title="Total lap time",
    )
fig.show()

In [14]:
fig = go.Figure()

# Add a box trace
fig.add_trace(
    go.Box(
        y=lap_times_selected_driver_circuit["milliseconds"], name="Lap times for Aus GP"
    )
)

# Customize the layout
fig.update_layout(
    title="Box Plot with plotly.graph_objects",
    yaxis_title="Values",
)

# Show the figure
fig.show()

In [15]:
lap_times_selected_driver_circuit[lap_times_selected_driver_circuit["raceId"] == 948]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
111775     948        20    1         1         96916  2016      1          1   
111776     948        20    2         1         91664  2016      1          1   
111777     948        20    3         1         92167  2016      1          1   
111778     948        20    4         1         92014  2016      1          1   
111779     948        20    5         1         92273  2016      1          1   
111780     948        20    6         1         92204  2016      1          1   
111781     948        20    7         1         92080  2016      1          1   
111782     948        20    8         1         92289  2016      1          1   
111783     948        20    9         1         92578  2016      1          1   
111784     948        20   10         1         92571  2016      1          1   
111785     948        20   11         1         92960  2016      1          1   
111786     948        20   12         1         93014  2016      1          1   
111787     948        20   13         3        110574  2016      1          1   
111788     948        20   14         3         95604  2016      1          1   
111789     948        20   15         3         90757  2016      1          1   
111790     948        20   16         1         91809  2016      1          1   
111791     948        20   17         1         99423  2016      1          1   
111792     948        20   18         1        201551  2016      1          1   
111793     948        20   19         1       1213527  2016      1          1   
111794     948        20   20         1         90524  2016      1          1   
111795     948        20   21         1         90374  2016      1          1   
111796     948        20   22         1         90207  2016      1          1   
111797     948        20   23         1         89951  2016      1          1   
111798     948        20   24         1         90185  2016      1          1   
111799     948        20   25         1         90719  2016      1          1   
111800     948        20   26         1         91764  2016      1          1   
111801     948        20   27         1         91454  2016      1          1   
111802     948        20   28         1         91507  2016      1          1   
111803     948        20   29         1         91809  2016      1          1   
111804     948        20   30         1         92003  2016      1          1   
111805     948        20   31         1         92228  2016      1          1   
111806     948        20   32         1         92227  2016      1          1   
111807     948        20   33         1         92795  2016      1          1   
111808     948        20   34         1         92937  2016      1          1   
111809     948        20   35         4        113109  2016      1          1   
111810     948        20   36         4         94747  2016      1          1   
111811     948        20   37         4         90251  2016      1          1   
111812     948        20   38         4         90612  2016      1          1   
111813     948        20   39         4         90627  2016      1          1   
111814     948        20   40         4         91064  2016      1          1   
111815     948        20   41         4         91220  2016      1          1   
111816     948        20   42         3         91104  2016      1          1   
111817     948        20   43         3         90814  2016      1          1   
111818     948        20   44         3         91196  2016      1          1   
111819     948        20   45         3         90779  2016      1          1   
111820     948        20   46         3         90725  2016      1          1   
111821     948        20   47         3         90590  2016      1          1   
111822     948        20   48         3         90463  2016      1          1   
111823     948        20   49         3

In [16]:
lap_times_selected_driver_circuit[lap_times_selected_driver_circuit["raceId"] == 1]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
343523       1        20    1         2         99647  2009      1          1   
343524       1        20    2         2         91173  2009      1          1   
343525       1        20    3         2         89752  2009      1          1   
343526       1        20    4         2         88999  2009      1          1   
343527       1        20    5         2         88849  2009      1          1   
343528       1        20    6         2         88424  2009      1          1   
343529       1        20    7         2         88235  2009      1          1   
343530       1        20    8         2         88140  2009      1          1   
343531       1        20    9         2         88331  2009      1          1   
343532       1        20   10         2         88970  2009      1          1   
343533       1        20   11         2         88862  2009      1          1   
343534       1        20   12         2         88387  2009      1          1   
343535       1        20   13         2         88260  2009      1          1   
343536       1        20   14         2         88457  2009      1          1   
343537       1        20   15         2         88279  2009      1          1   
343538       1        20   16         2        110990  2009      1          1   
343539       1        20   17         2         95628  2009      1          1   
343540       1        20   18         2         90580  2009      1          1   
343541       1        20   19         2         94856  2009      1          1   
343542       1        20   20         2        144788  2009      1          1   
343543       1        20   21         2        106868  2009      1          1   
343544       1        20   22         2        158375  2009      1          1   
343545       1        20   23         2        151909  2009      1          1   
343546       1        20   24         2        142185  2009      1          1   
343547       1        20   25         2         93553  2009      1          1   
343548       1        20   26         2         91452  2009      1          1   
343549       1        20   27         2         90116  2009      1          1   
343550       1        20   28         2         89431  2009      1          1   
343551       1        20   29         2         89242  2009      1          1   
343552       1        20   30         2         89120  2009      1          1   
343553       1        20   31         2         88686  2009      1          1   
343554       1        20   32         2         88819  2009      1          1   
343555       1        20   33         2         88875  2009      1          1   
343556       1        20   34         2         88604  2009      1          1   
343557       1        20   35         2         88528  2009      1          1   
343558       1        20   36         2         88173  2009      1          1   
343559       1        20   37         2         88557  2009      1          1   
343560       1        20   38         2         88459  2009      1          1   
343561       1        20   39         2         88369  2009      1          1   
343562       1        20   40         2         88448  2009      1          1   
343563       1        20   41         2         88852  2009      1          1   
343564       1        20   42         2         89082  2009      1          1   
343565       1        20   43         2         89102  2009      1          1   
343566       1        20   44         2         88976  2009      1          1   
343567       1        20   45         2        106765  2009      1          1   
343568       1        20   46         2         94308  2009      1          1   
343569       1        20   47         2         89862  2009      1          1   
343570       1        20   48         2         89555  2009      1          1   
343571       1        20   49         2

In [17]:
master_laptimes_pitstop_df[
    (master_laptimes_pitstop_df["raceId"] == 948)
    & (master_laptimes_pitstop_df["lap"] == 18)
]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
111792     948        20   18         1        201551  2016      1          1   
111849     948         8   18         3        188276  2016      1          1   
111870     948         3   18         2        199132  2016      1          1   
111927     948       830   18         5        189398  2016      1          1   
111984     948        13   18         8       1243269  2016      1          1   
112041     948         1   18         7       1243047  2016      1          1   
112098     948       832   18         6       1242495  2016      1          1   
112155     948       807   18        10       1229799  2016      1          1   
112212     948       817   18         4        190570  2016      1          1   
112285     948       815   18        13       1221249  2016      1          1   
112342     948        18   18        15       1223874  2016      1          1   
112398     948       835   18        12       1223356  2016      1          1   
112455     948       836   18        17       1223494  2016      1          1   
112511     948       828   18        14       1222582  2016      1          1   
112549     948       831   18        16       1222819  2016      1          1   
112605     948       822   18        11       1231528  2016      1          1   
112662     948       154   18         9       1241349  2016      1          1   
112752     948       825   18        18        500454  2016      1          1   

                         name        date number  statusId  \
111792  Australian Grand Prix  2016-03-20      5         1   
111849  Australian Grand Prix  2016-03-20      7         5   
111870  Australian Grand Prix  2016-03-20      6         1   
111927  Australian Grand Prix  2016-03-20     33         1   
111984  Australian Grand Prix  2016-03-20     19         1   
112041  Australian Grand Prix  2016-03-20     44         1   
112098  Australian Grand Prix  2016-03-20     55         1   
112155  Australian Grand Prix  2016-03-20     27         1   
112212  Australian Grand Prix  2016-03-20      3         1   
112285  Australian Grand Prix  2016-03-20     11         1   
112342  Australian Grand Prix  2016-03-20     22        11   
112398  Australian Grand Prix  2016-03-20     30         1   
112455  Australian Grand Prix  2016-03-20     94        11   
112511  Australian Grand Prix  2016-03-20      9         5   
112549  Australian Grand Prix  2016-03-20     12        11   
112605  Australian Grand Prix  2016-03-20     77         1   
112662  Australian Grand Prix  2016-03-20      8         1   
112752  Australian Grand Prix  2016-03-20     20         1   

        pitStopMilliseconds  isPitStop  
111792            1089312.0       True  
111849            1089365.0       True  
111870            1089303.0       True  
111927            1089372.0       True  
111984            1089805.0       True  
112041            1090087.0       True  
112098            1089971.0       True  
112155            1089155.0       True  
112212            1089822.0       True  
112285            1087311.0       True  
112342            1084466.0       True  
112398            1088294.0       True  
112455            1082140.0       True  
112511            1086875.0       True  
112549            1082337.0       True  
112605            1088989.0       True  
112662            1089417.0       True  
112752                  0.0      False

In [18]:
master_laptimes_pitstop_df[
    (master_laptimes_pitstop_df["raceId"] == 948)
    & (master_laptimes_pitstop_df["driverId"] == 825)
]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
112735     948       825    1        21        180423  2016      1          1   
112736     948       825    2        21        106207  2016      1          1   
112737     948       825    3        21         97229  2016      1          1   
112738     948       825    4        21         94720  2016      1          1   
112739     948       825    5        21         95346  2016      1          1   
112740     948       825    6        21        103453  2016      1          1   
112741     948       825    7        21         94917  2016      1          1   
112742     948       825    8        21         95742  2016      1          1   
112743     948       825    9        21         95633  2016      1          1   
112744     948       825   10        21         97304  2016      1          1   
112745     948       825   11        21         97254  2016      1          1   
112746     948       825   12        21         95206  2016      1          1   
112747     948       825   13        21         94927  2016      1          1   
112748     948       825   14        21         97999  2016      1          1   
112749     948       825   15        21         95084  2016      1          1   
112750     948       825   16        21        135143  2016      1          1   
112751     948       825   17        19        729123  2016      1          1   
112752     948       825   18        18        500454  2016      1          1   
112753     948       825   19        18        120667  2016      1          1   
112754     948       825   20        18         96001  2016      1          1   
112755     948       825   21        17         95554  2016      1          1   
112756     948       825   22        16         93453  2016      1          1   
112757     948       825   23        16         94824  2016      1          1   
112758     948       825   24        16         94813  2016      1          1   
112759     948       825   25        15         95592  2016      1          1   
112760     948       825   26        15         94649  2016      1          1   
112761     948       825   27        14         94562  2016      1          1   
112762     948       825   28        14         94012  2016      1          1   
112763     948       825   29        14         93727  2016      1          1   
112764     948       825   30        13         93539  2016      1          1   
112765     948       825   31        13         93508  2016      1          1   
112766     948       825   32        13         93585  2016      1          1   
112767     948       825   33        13         93838  2016      1          1   
112768     948       825   34        13         93718  2016      1          1   
112769     948       825   35        13         93306  2016      1          1   
112770     948       825   36        13         93004  2016      1          1   
112771     948       825   37        13         92789  2016      1          1   
112772     948       825   38        13         92783  2016      1          1   
112773     948       825   39        13         92791  2016      1          1   
112774     948       825   40        13         93244  2016      1          1   
112775     948       825   41        13         93320  2016      1          1   
112776     948       825   42        13         92765  2016      1          1   
112777     948       825   43        13         92715  2016      1          1   
112778     948       825   44        13         93016  2016      1          1   
112779     948       825   45        13         92452  2016      1          1   
112780     948       825   46        13         92797  2016      1          1   
112781     948       825   47        13         92459  2016      1          1   
112782     948       825   48        13         92815  2016      1          1   
112783     948       825   49        13

In [19]:
lap_times_selected_driver_circuit[lap_times_selected_driver_circuit["raceId"] == 900]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
72699     900        20    1        15        120977  2014      1          1   
72700     900        20    2        16        109947  2014      1          1   
72701     900        20    3        16        111460  2014      1          1   

                        name        date number  statusId  \
72699  Australian Grand Prix  2014-03-16      1         5   
72700  Australian Grand Prix  2014-03-16      1         5   
72701  Australian Grand Prix  2014-03-16      1         5   

       pitStopMilliseconds  isPitStop  
72699                  0.0      False  
72700                  0.0      False  
72701                  0.0      False

In [20]:
lap_times_selected_driver_circuit[
    (lap_times_selected_driver_circuit["raceId"] == 948)
    & (lap_times_selected_driver_circuit["lap"] == 18)
]

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
111792     948        20   18         1        201551  2016      1          1   

                         name        date number  statusId  \
111792  Australian Grand Prix  2016-03-20      5         1   

        pitStopMilliseconds  isPitStop  
111792            1089312.0       True

In [21]:
## work on the outlier
lap17_time = lap_times_selected_driver_circuit[
    (lap_times_selected_driver_circuit["raceId"] == 948)
    & (lap_times_selected_driver_circuit["lap"] == 17)
]["milliseconds"].values[0]

lap20_time = lap_times_selected_driver_circuit[
    (lap_times_selected_driver_circuit["raceId"] == 948)
    & (lap_times_selected_driver_circuit["lap"] == 20)
]["milliseconds"].values[0]

lap_times_selected_driver_circuit.loc[
    (lap_times_selected_driver_circuit["raceId"] == 948)
    & (lap_times_selected_driver_circuit["lap"] == 18),
    "milliseconds",
] = (lap17_time + lap20_time) / 2

lap_times_selected_driver_circuit.loc[
    (lap_times_selected_driver_circuit["raceId"] == 948)
    & (lap_times_selected_driver_circuit["lap"] == 19),
    "milliseconds",
] = (lap17_time + lap20_time) / 2

In [22]:
fig = go.Figure()

for race_id in list_race_id:

    lap_times_race = lap_times_selected_driver_circuit[
        lap_times_selected_driver_circuit["raceId"] == race_id
    ]

    fig.add_trace(
        go.Scatter(
            x=lap_times_race["lap"],
            y=lap_times_race["milliseconds"],
            mode="lines+markers",
            name=f"race id: {race_id}",
        )
    )

    fig.update_layout(
        title="Laptimes by each lap",
        xaxis_title="Lap number",
        yaxis_title="Total lap time",
    )
fig.show()

In [23]:
fig = go.Figure()

# Add a box trace
fig.add_trace(
    go.Box(
        y=lap_times_selected_driver_circuit["milliseconds"], name="Lap times for Aus GP"
    )
)

# Customize the layout
fig.update_layout(
    title="Box Plot with plotly.graph_objects",
    yaxis_title="Values",
)

# Show the figure
fig.show()

In [24]:
lap_times_selected_driver_circuit

raceId  driverId  lap  position  milliseconds  year  round  circuitId  \
0          841        20    1         1       98109.0  2011      1          1   
1          841        20    2         1       93006.0  2011      1          1   
2          841        20    3         1       92713.0  2011      1          1   
3          841        20    4         1       92803.0  2011      1          1   
4          841        20    5         1       92342.0  2011      1          1   
...        ...       ...  ...       ...           ...   ...    ...        ...   
517395    1076        20   18        15       85367.0  2022      3          1   
517396    1076        20   19        15       85503.0  2022      3          1   
517397    1076        20   20        15       85398.0  2022      3          1   
517398    1076        20   21        13       85505.0  2022      3          1   
517399    1076        20   22        12       87005.0  2022      3          1   

                         name        date number  statusId  \
0       Australian Grand Prix  2011-03-27      1         1   
1       Australian Grand Prix  2011-03-27      1         1   
2       Australian Grand Prix  2011-03-27      1         1   
3       Australian Grand Prix  2011-03-27      1         1   
4       Australian Grand Prix  2011-03-27      1         1   
...                       ...         ...    ...       ...   
517395  Australian Grand Prix  2022-04-10      5         3   
517396  Australian Grand Prix  2022-04-10      5         3   
517397  Australian Grand Prix  2022-04-10      5         3   
517398  Australian Grand Prix  2022-04-10      5         3   
517399  Australian Grand Prix  2022-04-10      5         3   

        pitStopMilliseconds  isPitStop  
0                       0.0      False  
1                       0.0      False  
2                       0.0      False  
3                       0.0      False  
4                       0.0      False  
...                     ...        ...  
517395                  0.0      False  
517396                  0.0      False  
517397                  0.0      False  
517398                  0.0      False  
517399                  0.0      False  

[568 rows x 14 columns]

# Feature engineering

In [25]:
engineer_data_obj = engineerFeaturesForTraining(config=config)


engineered_lap_times_df, encoder, encoder_columns = engineer_data_obj.engineer_data(
    lap_times_data=lap_times_selected_driver_circuit
)

In [26]:
engineered_lap_times_df

raceId  lap  position  milliseconds  year  milliseconds_1_prior  \
1         1    2         2       91173.0  2009               99647.0   
2         1    3         2       89752.0  2009               91173.0   
3         1    4         2       88999.0  2009               89752.0   
4         1    5         2       88849.0  2009               88999.0   
5         1    6         2       88424.0  2009               88849.0   
..      ...  ...       ...           ...   ...                   ...   
560    1076   18        15       85367.0  2022               85189.0   
561    1076   19        15       85503.0  2022               85367.0   
562    1076   20        15       85398.0  2022               85503.0   
563    1076   21        13       85505.0  2022               85398.0   
564    1076   22        12       87005.0  2022               85505.0   

     lap_number_1_prior  position_1_prior_lap  month  day  isPitStop_False  \
1                   1.0                   2.0      3   29              1.0   
2                   2.0                   2.0      3   29              1.0   
3                   3.0                   2.0      3   29              1.0   
4                   4.0                   2.0      3   29              1.0   
5                   5.0                   2.0      3   29              1.0   
..                  ...                   ...    ...  ...              ...   
560                17.0                  16.0      4   10              1.0   
561                18.0                  15.0      4   10              1.0   
562                19.0                  15.0      4   10              1.0   
563                20.0                  15.0      4   10              1.0   
564                21.0                  13.0      4   10              1.0   

     isPitStop_True  statusId_1  statusId_3  statusId_4  statusId_36  
1               0.0         0.0         0.0         1.0          0.0  
2               0.0         0.0         0.0         1.0          0.0  
3               0.0         0.0         0.0         1.0          0.0  
4               0.0         0.0         0.0         1.0          0.0  
5               0.0         0.0         0.0         1.0          0.0  
..              ...         ...         ...         ...          ...  
560             0.0         0.0         1.0         0.0          0.0  
561             0.0         0.0         1.0         0.0          0.0  
562             0.0         0.0         1.0         0.0          0.0  
563             0.0         0.0         1.0         0.0          0.0  
564             0.0         0.0         1.0         0.0          0.0  

[554 rows x 16 columns]

In [27]:
fig = go.Figure()

for race_id in list_race_id:

    lap_times_race = engineered_lap_times_df[
        engineered_lap_times_df["raceId"] == race_id
    ]

    fig.add_trace(
        go.Scatter(
            x=lap_times_race["lap"],
            y=lap_times_race["milliseconds"],
            mode="lines+markers",
            name=f"race id: {race_id}",
        )
    )

    fig.add_trace(
        go.Scatter(
            x=lap_times_race["lap"],
            y=lap_times_race["milliseconds_1_prior"],
            mode="lines+markers",
            name=f"race id: {race_id} 1 prior",
        )
    )

    fig.update_layout(
        title="Laptimes by each lap and prior lap",
        xaxis_title="Lap number",
        yaxis_title="Total lap time",
    )
fig.show()

# Spliting into train test and validation

In [28]:
split_obj = splitData()

train_data, test_data = split_obj.train_test_split(
    data=engineered_lap_times_df, race_id=338
)

training_set, validation_set = split_obj.train_validation_split(train_data=train_data)

# Transform data into modelling data
- scaling 
- sequencing

In [29]:
## training_set trainformation

In [30]:
data_transform_obj = transformData(
    n_steps_input=config.get("N_STEP_INPUT"),
    n_steps_output=config.get("N_STEP_OUTPUT"),
    config=config,
)

scaled_input_df_train, scaled_output_df_train = (
    data_transform_obj.create_scaled_input_output_data(data=training_set, train=True)
)


scaled_input_df_val, scaled_output_df_val = (
    data_transform_obj.create_scaled_input_output_data(data=validation_set, train=False)
)

INFO:root:scaler_dict.pkl saved to ../artifacts/


In [41]:
scaled_input_df_val

year_scaled  day_scaled  lap_scaled  position_scaled  \
0      -1.660550    1.495531    1.000000         0.055556   
1      -1.660550    1.495531    1.022727         0.055556   
2      -1.660550    1.495531    1.045455         0.055556   
3      -1.660550    1.495531    1.068182         0.055556   
4      -1.660550    1.495531    1.090909         0.055556   
..           ...         ...         ...              ...   
107     2.102348   -2.096095    0.363636         0.777778   
108     2.102348   -2.096095    0.386364         0.777778   
109     2.102348   -2.096095    0.409091         0.777778   
110     2.102348   -2.096095    0.431818         0.666667   
111     2.102348   -2.096095    0.454545         0.611111   

     milliseconds_1_prior_scaled  lap_number_1_prior_scaled  \
0                       0.273641                   1.000000   
1                       0.112934                   1.022727   
2                       0.055577                   1.045455   
3                       0.051616                   1.068182   
4                       0.052558                   1.090909   
..                           ...                        ...   
107                    -0.004709                   0.363636   
108                    -0.002412                   0.386364   
109                    -0.000658                   0.409091   
110                    -0.002013                   0.431818   
111                    -0.000632                   0.454545   

     position_1_prior_lap_scaled  month_sin     month_cos  isPitStop_False  \
0                       0.055556   1.000000  6.123234e-17              1.0   
1                       0.055556   1.000000  6.123234e-17              1.0   
2                       0.055556   1.000000  6.123234e-17              1.0   
3                       0.055556   1.000000  6.123234e-17              1.0   
4                       0.055556   1.000000  6.123234e-17              1.0   
..                           ...        ...           ...              ...   
107                     0.833333   0.866025 -5.000000e-01              1.0   
108                     0.777778   0.866025 -5.000000e-01              1.0   
109                     0.777778   0.866025 -5.000000e-01              1.0   
110                     0.777778   0.866025 -5.000000e-01              1.0   
111                     0.666667   0.866025 -5.000000e-01              1.0   

     raceId  statusId_4  statusId_1  isPitStop_True  statusId_3  statusId_36  
0         1         1.0         0.0             0.0         0.0          0.0  
1         1         1.0         0.0             0.0         0.0          0.0  
2         1         1.0         0.0             0.0         0.0          0.0  
3         1         1.0         0.0             0.0         0.0          0.0  
4         1         1.0         0.0             0.0         0.0          0.0  
..      ...         ...         ...             ...         ...          ...  
107    1076         0.0         0.0             0.0         1.0          0.0  
108    1076         0.0         0.0             0.0         1.0          0.0  
109    1076         0.0         0.0             0.0         1.0          0.0  
110    1076         0.0         0.0             0.0         1.0          0.0  
111    1076         0.0         0.0             0.0         1.0          0.0  

[112 rows x 16 columns]

In [32]:
x_sequential_train, y_sequential_train = data_transform_obj.create_sequence(
    scaled_input_df=scaled_input_df_train, scaled_output_df=scaled_output_df_train
)

x_sequential_val, y_sequential_val = data_transform_obj.create_sequence(
    scaled_input_df=scaled_input_df_val, scaled_output_df=scaled_output_df_val
)

In [33]:
x_train = torch.Tensor(x_sequential_train)
y_train = torch.Tensor(y_sequential_train)

x_train = torch.reshape(
    x_train,
    (
        x_train.shape[0],
        2,
        x_train.shape[2],
    ),
)

x_validation = torch.Tensor(x_sequential_val)
y_validation = torch.Tensor(y_sequential_val)

x_validation = torch.reshape(
    x_validation,
    (
        x_validation.shape[0],
        2,
        x_validation.shape[2],
    ),
)

In [34]:
train_obj = train(config=config)

train_data_loader, validation_data_loader = train_obj.create_data_loader(
    batch_size=8,
    x_train=x_train,
    y_train=y_train,
    x_validation=x_validation,
    y_validation=y_validation,
)

In [35]:
x_train.shape[2]

15

In [36]:
lstm_model = LSTM(
    num_classes=config.get("N_STEP_OUTPUT"),
    input_size=x_train.shape[2],
    hidden_size_layer=8,
    num_layers=config.get("NUM_LAYERS"),
    dropout_rate=0.1,
)
lstm_model.to(device)

loss_fn = torch.nn.MSELoss()

optimizer = torch.optim.Adam(lstm_model.parameters(), lr=0.001)

validation_loss = train_obj.train_validation_loop(
    n_epochs=10,
    lstm_model=lstm_model,
    optimizer=optimizer,
    loss_fn=loss_fn,
    train_loader=train_data_loader,
    validation_loader=validation_data_loader,
    device=device,
)

Epoch num: 0
Batch 1, train loss: 0.0017917284276336432
Batch 2, train loss: 0.0018878477858379483
Batch 3, train loss: 0.0015220972709357738
Batch 4, train loss: 0.0023793629370629787
Batch 5, train loss: 0.0014914677012711763
Batch 6, train loss: 0.001568135223351419
Batch 7, train loss: 0.0013983328826725483
Batch 8, train loss: 0.001572939450852573
Batch 9, train loss: 0.0020486374851316214
Batch 10, train loss: 0.001302922610193491
Batch 11, train loss: 0.0023481135722249746
Batch 12, train loss: 0.0011498351814225316
Batch 13, train loss: 0.0012275032931938767
Batch 14, train loss: 0.001193415024317801
Batch 15, train loss: 0.0012467049527913332
Batch 16, train loss: 0.001421367283910513
Batch 17, train loss: 0.0009192790021188557
Batch 18, train loss: 0.0009815662633627653
Batch 19, train loss: 0.0013636728981509805
Batch 20, train loss: 0.0008283961797133088
Batch 21, train loss: 0.0014847315615043044
Batch 22, train loss: 0.0009862756123766303
Batch 23, train loss: 0.000952734

INFO:root:model.pkl saved to ../artifacts/


Batch 10, train loss: 6.820795533712953e-05
Batch 11, train loss: 0.00020760226470883936
Batch 12, train loss: 0.00016096467152237892
Batch 13, train loss: 0.0004527407872956246
Batch 14, train loss: 0.0002731763815972954
Batch 15, train loss: 4.907527909381315e-05
Batch 16, train loss: 0.00021205983648542315
Batch 17, train loss: 0.0003569457621779293
Batch 18, train loss: 0.0005265909712761641
Batch 19, train loss: 8.239853195846081e-05
Batch 20, train loss: 0.0006219689385034144
Batch 21, train loss: 0.0007536853663623333
Batch 22, train loss: 0.00030931062065064907
Batch 23, train loss: 0.001092849182896316
Batch 24, train loss: 0.0006307278526946902
Batch 25, train loss: 0.0002553887024987489
Batch 26, train loss: 0.00011588749475777149
Batch 27, train loss: 6.157558527775109e-05
Batch 28, train loss: 0.00010390221723355353
Batch 29, train loss: 9.617996693123132e-05
Batch 30, train loss: 0.00012965429050382227
Batch 31, train loss: 0.00010703235602704808
Batch 32, train loss: 0.0

In [37]:
infer_obj = makeInference(config=config)

prediction_tensor, actual_sequential = infer_obj.perform_inference(
    test_data=test_data, device=device
)

tensor([[0.1477, 0.2981, 0.0000, 0.0000, 0.0000],
        [0.1114, 0.2649, 0.0000, 0.0000, 0.0000],
        [0.1275, 0.2189, 0.0000, 0.0000, 0.0000],
        [0.1385, 0.0000, 0.0000, 0.0000, 0.0029],
        [0.2136, 0.0000, 0.0000, 0.0000, 0.0308],
        [0.2246, 0.0000, 0.0000, 0.0000, 0.0312],
        [0.2503, 0.0000, 0.0000, 0.0000, 0.0510],
        [0.2591, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2302, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2616, 0.0000, 0.0000, 0.0000, 0.0740],
        [0.2849, 0.0000, 0.0000, 0.0000, 0.0816],
        [0.2936, 0.0000, 0.0000, 0.0000, 0.0819],
        [0.3017, 0.0000, 0.0000, 0.0000, 0.0761],
        [0.3076, 0.0000, 0.0000, 0.0000, 0.0623],
        [0.3133, 0.0000, 0.0000, 0.0000, 0.0664],
        [0.3229, 0.0000, 0.0000, 0.0000, 0.0669],
        [0.3310, 0.0000, 0.0000, 0.0000, 0.0636],
        [0.3382, 0.0000, 0.0000, 0.0000, 0.0601],
        [0.3454, 0.0000, 0.0000, 0.0000, 0.0567]])


In [38]:
prediction_tensor

array([[ 96690.39001092, 108404.16316617,  85189.        ,
         85189.        ,  85189.        ],
       [ 93864.57443706, 105820.15895972,  85189.        ,
         85189.        ,  85189.        ],
       [ 95119.02374397, 102236.41331172,  85189.        ,
         85189.        ,  85189.        ],
       [ 95977.93654197,  85189.        ,  85189.        ,
         85189.        ,  85414.36435786],
       [101825.88968657,  85189.        ,  85189.        ,
         85189.        ,  87588.84876087],
       [102682.14961007,  85189.        ,  85189.        ,
         85189.        ,  87622.71062659],
       [104679.72233069,  85189.        ,  85189.        ,
         85189.        ,  89162.71355748],
       [105371.15937042,  85189.        ,  85189.        ,
         85189.        ,  85189.        ],
       [103113.59334397,  85189.        ,  85189.        ,
         85189.        ,  85189.        ],
       [105563.49161115,  85189.        ,  85189.        ,
         85189.        

In [39]:
actual_sequential

[array([156229., 150999., 104978., 103250., 102775.]),
 array([150999., 104978., 103250., 102775., 101476.]),
 array([104978., 103250., 102775., 101476., 121768.]),
 array([103250., 102775., 101476., 121768., 103572.]),
 array([102775., 101476., 121768., 103572.,  93057.]),
 array([101476., 121768., 103572.,  93057.,  92439.]),
 array([121768., 103572.,  93057.,  92439.,  91856.]),
 array([103572.,  93057.,  92439.,  91856.,  92287.]),
 array([93057., 92439., 91856., 92287., 93925.]),
 array([92439., 91856., 92287., 93925., 92447.]),
 array([91856., 92287., 93925., 92447., 91866.]),
 array([92287., 93925., 92447., 91866., 91812.]),
 array([93925., 92447., 91866., 91812., 91744.]),
 array([92447., 91866., 91812., 91744., 91626.]),
 array([91866., 91812., 91744., 91626., 91558.]),
 array([91812., 91744., 91626., 91558., 91556.]),
 array([91744., 91626., 91558., 91556., 92064.]),
 array([91626., 91558., 91556., 92064., 92939.]),
 array([91558., 91556., 92064., 92939., 92391.])]